Restaurant.create(name: 'Tuc Craft Kitchen', address: '60 W Cordova St, Vancouver, BC V6B 1C9')
Restaurant.create(name: 'Salt Tasting Room', address: '45 Blood Alley Square, Vancouver, BC V6B 1C7')
Restaurant.create(name: 'Revel Room', address: '238 Abbott St, Vancouver, BC V6B 2K8')
Hostess.create(username: 'Mary', password: '1234', restaurant_id: 1)
Hostess.create(username: 'Anne', password: '5678', restaurant_id: 1)
Hostess.create(username: 'Adele', password: '4321', restaurant_id: 2)
Hostess.create(username: 'Holly', password: '8765', restaurant_id: 3)